### PR TITLE
Footer added

### LINKED ISSUE #12: Make matching footer for the website
The footer should consist of name of the organization,name of the app, contact no. and a copy right statement. You can arrange the components however you want just match the theme.

### PR DESCRIPTION
**Pull request by pradhuman1**
__12__ 

Fixes #12

#### Short description of what this resolves:
Footer Added

#### Changes proposed in this pull request and/or Screenshots of changes:

-Footer added consist of name of the organization,name of the app, contact no. and a copy right statement
-
-

### CODE REVIEW

**Comment by abhishekmsingh** [comment]
@pradhuman1 Can you provide a live link for your repo website

**Comment by pradhuman1** [comment]
https://pradhuman1.github.io/libook/pages/

**Comment by abhishekmsingh** [comment]
@pradhuman1 please adjust the background color of the footer to be inline with the theme of the website. Make it black, or grey, or whatever looks good. also adjust the font size. Keep some space between the last title and the footer. Note that you can use bootstrap. You can visit some websites to get idea. Look at the footer of github itself.

**Comment by shuba400** [comment]
I can do that
maybe after a day ;) 
@pradhuman1

**Pull request closed without merging**
