### PR TITLE
Improved the Cards

### LINKED ISSUE #50: Improving the cards
Currently the cards show only the title of the book which is not very helpful. Use the bootstrap 4 cards and design them as follows:
1. The card header should be the title.
2. The card body should be the details or summary of the title which is mentioned in the card header of that card.
3. The card footer should be the author's name.
Maintain the theme. Sub par styling wouldn't be accepted.

### PR DESCRIPTION
**Pull request by Rohini13**
__50__ 

Fixes #50 

#### Short description of what this resolves:
The Card only displayed the title of the book, which obviously isn't very informative.  

#### Changes proposed in this pull request and/or Screenshots of changes:

I have used bootstrap 4 cards, which now display the book title in the header, summary in the body and author's name in the footer.

Live Link: https://rohini13.github.io/libook/pages/

Screenshot (66)
-
-
-

### CODE REVIEW

**Comment by thesmallstar** [comment]
@abhiandthetruth

**Comment by abhishekmsingh** [comment]
image
The summary and author fields come undefined when I add something. Reload solves the problem. Please look into this issue.

**Comment by Rohini13** [comment]
@abhiandthetruth issue resolved.

**Comment by Rohini13** [comment]
@abhiandthetruth issue resolved.

**Pull request merged**
