### PR TITLE
Idea for Add title bar

### PR DESCRIPTION
**Pull request by pradhuman1**
__10__ 

Fixes #10

#### Short description of what this resolves:
Idea for Title bar

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by abhishekmsingh** [comment]
The website is supposed to handle multiple titles.

**Comment by pradhuman1** [comment]
What i want to say is that we should clear Field(Add title field)

**Comment by pradhuman1** [comment]
> What i want to say is that we should clear Field(Add title field)

After pressing 'enter'(or click add button)

**Comment by abhishekmsingh** [comment]
Ohk you got this one right, well I'll say you link this with the bugs issue so you can get 10 points for spotting it. And then I'm going to open this issue so you can claim it if you wasn't. Technically it's an enhancement though.

**Comment by pradhuman1** [comment]
sir i linked it with bugs issue

**Comment by abhishekmsingh** [comment]
Would you like to work on this issue, so that I can assign the issue to you when opened.

**Comment by pradhuman1** [comment]
yes sir

**Pull request merged**
