### PR TITLE
Added Details

### LINKED ISSUE #36: Add details functionality and change how things are stored
Add a text field/area which takes details, author, page no for the titles as input. Position them accordingly. You may use the space taken by "Lorem ipsum.....". Change the add titles button to add book. Now change the local storage such that the title is the key and the value is json(as a string of course) consisting of the following fields:
{
"title": title,
"details": details,
"img": img,
"addedAt": date and time of addition, 
"startedAt": date and time of addition,
"finishedAt": date and time of finishing,
"author": Author,
"Pages": no of pages,
}
default value of fields img, startedAt, finishedAt should be "not available" or anything indicative of the same.

### PR DESCRIPTION
**Pull request by pradhuman1**
__36__ 

Fixes #36

#### Short description of what this resolves:

Details Added

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by pradhuman1** [comment]
https://pradhuman1.github.io/libook/pages/

**Comment by abhishekmsingh** [comment]
@pradhuman1 the search functionality is broken. The styling is unacceptable. You cannot make a type text input to type text area input just by changing the size of it, use the type attribute.. Don't rush it, consider this project to be your own, I will give you ample time but please do it properly. Are you going to work on this further?

**Comment by pradhuman1** [comment]
yes

**Comment by pradhuman1** [comment]
yes

**Comment by pradhuman1** [comment]
Sir I will fix Search function but please give some idea about styling

**Comment by abhiandthetruth** [comment]
I want an update tomorrow noon.

**Comment by abhishekmsingh** [comment]
Ok I will try

**Comment by abhishekmsingh** [comment]
image
I am not an expert in styling but something like this would be decent. The right hand area would be for cover image uploading(issue coming up not in this issue). I cannot give the code obviously. What do you think?

**Comment by abhishekmsingh** [comment]
@pradhuman1 I wan't an update till tomorrow noon.

**Comment by pradhuman1** [comment]
Check this : https://pradhuman1.github.io/libook/pages/

**Comment by abhishekmsingh** [comment]
You can remove the page number field and add the demo text on the right side

**Comment by pradhuman1** [comment]
Check this : https://pradhuman1.github.io/libook/pages/

**Comment by abhishekmsingh** [comment]
image
You lost the responsiveness once you hardcoded the css. Well I'll let that slide this time. Since you have a lot of commits, you need to squash them. Squash the commits and I'll merge them.

**Comment by pradhuman1** [comment]
Sir how to squash commits

**Comment by abhishekmsingh** [comment]
Google it.

**Comment by abhishekmsingh** [comment]
https://www.google.com/amp/s/blog.liplex.de/how-to-squash-already-pushed-commits/amp/

**Comment by pradhuman1** [comment]
Sir i squashed

**Pull request merged**
