### PR TITLE
Search By option added

### LINKED ISSUE #57: introduce search by option
Issue assigned to @pradhuman1 since he suggested the feature. Please style properly and use DRY principles. I don't know how it will be implemented its onto you.

### PR DESCRIPTION
**Pull request by pradhuman1**
__57__ 

Fixes #57

#### Short description of what this resolves:
Search by Option added

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by pradhuman1** [comment]
https://pradhuman1.github.io/libook/pages/

**Comment by pradhuman1** [comment]
Made responsive also
https://pradhuman1.github.io/libook/pages/

**Comment by abhishekmsingh** [comment]
@pradhuman1 well done, just one issue can you close the search by selection menu after selection or maybe highlight the selection

**Comment by pradhuman1** [comment]
Please Review now

**Pull request merged**
