### PR TITLE
offline support

### LINKED ISSUE #7: Make Bootstrap available offline
Just in case somebody doesn't have internet connection, the ui should not go down when locally hosted. To ensure that remove the bootstrap cdn and download the bootstrap __4__ files. Make sure you download the compiled files not source. You must place the css contents in 'styles/bootstrap-css/' and scripts in 'scripts/bootsrap-js/' directly. Link those to index.html. The website should render properly without internet connection.

### PR DESCRIPTION
**Pull request by shuba400**
__7__

Fixes #7 

#### Short description of what this resolves:

Added the bootstrap 4 css files and js along with jQuery in place of cdn
Hence enabling offline hostage of site

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by abhishekmsingh** [comment]
Looks good to me. Just that can you provide me a live link of your repo. See https://guides.github.com/features/pages/ for how to do it.

**Comment by abhishekmsingh** [comment]
And yes you have to replace ISSUENUMBER in the template by the actual issue number. So please edit your pr description.

**Comment by shuba400** [comment]
Corrected Issue Number

**Comment by abhishekmsingh** [comment]
@shuba400 just comment out any cdn link in the file index.html. For generating live link,
go to your repository settings, scroll down to github pages section and select master branch in the sources. The url you get just give me that. You can go to url/pages to check if it is working.

**Comment by shuba400** [comment]
https://shuba400.github.io/libook/
This is the link
I checked it myself on my pc and after commenting out cdn, there was no difference in the site.

Only thing that I have done additionally is also adding jquery script along with bootstrap javascript as from one of the video lectures I saw that for Bootstrap, jQuery is needed.

**Pull request merged**
