### PR TITLE
Integrate pdf.js viewer in view.html

### LINKED ISSUE #65: integrate pdf.js for pdf viewing
Add a webpage in pages folder integrated with pdf.js for pdf viewing. You can currently hard-code the pdf source to be any pdf file which you willl upload in resources. Make the page theme match that of our website if possible.

### PR DESCRIPTION
**Pull request by sggts04**
__65__ 

Fixes #65 

#### Short description of what this resolves:
Integrates pdf.js viewer in view.html. Currently a sample.pdf is being used.

#### Changes proposed in this pull request and/or Screenshots of changes:
Live Link: https://shreyasgupta.in/libook/pages/view.html

### CODE REVIEW

**Comment by sggts04** [comment]
@abhiandthetruth please review

**Comment by sggts04** [comment]
@abhiandthetruth please review

**Comment by abhishekmsingh** [comment]
@sggts04  well sorry if I didn't explain it well enough but this was not what I was expecting. You have to make a pdf-viewer not include it(sort of).  Use the html canvas element for rendering stuff.  Use the pdfjsLib(provided by pdfjs) object to load the pdf in an object and then call the getPage() of the object to get the current page, render it in the 2d context of the canvas. Add next, prev page functionality along with goto page number.  Style it properly and in sync with the website. You can use any sample pdf file currently to test. Please reply in affirmative if you still want to work on this issue. Otherwise say no. Good luck!.

**Comment by abhishekmsingh** [comment]
Also you can hardcode the scale currently.

**Comment by sggts04** [comment]
When I first started working on this, I did that only, but thought an actual iframe feature-rich viewer would be better so I changed it.

I still want to work on this @abhiandthetruth

**Comment by sggts04** [comment]
@abhiandthetruth updated the PR, please review

**Comment by abhishekmsingh** [comment]
@sggts04 ES6 syntax though not necessary is always preferable. The scale, context or the canvas variables are best when global. Well it's an issue for another day. But keep in mind that while contributing not only the functionality but the code-quality matters too. Well done.

**Pull request merged**
