### PR TITLE
Footer

### LINKED ISSUE #12: Make matching footer for the website
The footer should consist of name of the organization,name of the app, contact no. and a copy right statement. You can arrange the components however you want just match the theme.

### PR DESCRIPTION
**Pull request by pradhuman1**
__12__ 

Fixes #12

#### Short description of what this resolves:

Footer is added

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by pradhuman1** [comment]
https://pradhuman1.github.io/libook/pages/

**Comment by abhishekmsingh** [comment]
Just increase the height a bit and the task would be complete.

**Comment by abhishekmsingh** [comment]
You don't need to close the pr, just commit it and it will be updated

**Comment by abhishekmsingh** [comment]
@pradhuman1  Just a tip. Learn to squash your commits in your pr. It is quite important while contributing to big organization. Nice job there. Though it needed a little bit of bottom padding i think

**Pull request merged**
