### PR TITLE
Arrange the cards in a grid

### LINKED ISSUE #74: Arrange the cards in a grid
The cards below should be arranged in row and column layout

### PR DESCRIPTION
**Pull request by pradhuman1**
__74__ 

Fixes #74

#### Short description of what this resolves:

Cards arranged in row and column layout

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-https://pradhuman1.github.io/libook/pages/
-

### CODE REVIEW

**Comment by abhishekmsingh** [comment]
Sorry I just missed this pr, well apparently it's not what I desired. Here's the look I want.

**Comment by abhishekmsingh** [comment]
image
There should be rows with this format. You can use any dummy image you want for the card image. It's my fault for not being descriptive earlier. Of course you don't have to implement the Last updated functionality, you have to show the author there.

**Comment by pradhuman1** [comment]
What is meant by this " Of course you don't have to implement the Last updated functionality, you have to show the author there."
PLease Explain @abhiandthetruth

**Comment by abhishekmsingh** [comment]
In the sample image, the card footer mentions 'Last updated 3 mins ago', so just to avoid confusion I mentioned that

**Comment by pradhuman1** [comment]
@abhiandthetruth please review now

**Comment by pradhuman1** [comment]
@abhiandthetruth i changed the cards but each when a new book is added,its card is added in new line not in continuous with other cards.I tried to change it but it doesn't changes.

**Comment by abhishekmsingh** [comment]
Use bootstrap grid layout. You can refer this if it helps. All the best.
https://stackoverflow.com/questions/48639792/bootstrap-4-cards-as-grid-with-the-same-height-and-width

**Comment by pradhuman1** [comment]
@abhiandthetruth Done

**Comment by abhishekmsingh** [comment]
The bottom of the last row of cards gets covered by website footer. See into it.

**Comment by pradhuman1** [comment]
Sir when will Opencode end

**Comment by pradhuman1** [comment]
> The bottom of the last row of cards gets covered by website footer. See into it.

@abhiandthetruth  i tried very hard to do it but i am unable to do it.Please can you let it go

**Comment by abhishekmsingh** [comment]
Tonight

**Comment by abhishekmsingh** [comment]
> > The bottom of the last row of cards gets covered by website footer. See into it.
> 
> @abhiandthetruth i tried very hard to do it but i am unable to do it.Please can you let it go

Well points are given not for trying but for the output. It may sound harsh but that is the rule. The best I can do is give you 20 points instead of 30 since the card's form factor was also off from the given example image. The card title, the body , the footer have been applied same styling which isn't quite right. So summing it up the output isn't worth 30. Will you settle for 20?

**Comment by pradhuman1** [comment]
Ok sir 20 points will be good

**Pull request merged**
