### PR TITLE
made website responsive and fixed issues

### LINKED ISSUE #29: Make the website responsive
Go to the mobile view of the website and you can see how the search and add title buttons appear dis-oriented. Fix that. Note that the desktop view should not be affected.

### PR DESCRIPTION
**Pull request by blaze-assault**
__29__ 

Fixes #29 

#### Short description of what this resolves:
made website responsive and fixed issues.

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by blaze-assault** [comment]
https://blaze-assault.github.io/pages/index.html

here is the live link.
@abhiandthetruth  made a pr again please check

**Comment by abhiandthetruth** [comment]
Why is the search button sticking to the right border, give it some margin or padding.

**Comment by abhishekmsingh** [comment]
@blaze-assault change of plans, I need to work on other issues before this. You will get the points for your work but the changes you made won't be merged. Can you undo your changes and commit with some minor change so that I can merge it. I know it sounds harsh but I need to add more elements to the page and this pr is conflicting them. Can you do it?

**Comment by blaze-assault** [comment]
What should i change then?.i dont have to fix the moviel view??.i really
gave it time ,learnt new things and have worked hard for it. What change
should i make so that i  can get the points?

**Pull request closed without merging**
