### PR TITLE
Added book.html and linked it with every tile

### LINKED ISSUE #61: Add a page book.html and link it with every titles
On clicking a title, a get request should be send to book.html with query title=[book title]. And make book.html display the title name of which it was clicked.

### PR DESCRIPTION
**Pull request by untrulynoxiusmj**
__61__ 

Fixes #61

#### Short description of what this resolves:

Added book.html and linked it with every tile

#### Changes proposed in this pull request and/or Screenshots of changes:

live link :

https://untrulynoxiusmj.github.io/libook/pages/

### CODE REVIEW

**Comment by abhishekmsingh** [comment]
Sorry I didn't mention it properly in the issue, you have to make the whole card clickable

**Comment by untrulynoxiusmj** [comment]
Ok sir , i ll do that
Is the other functionality correct ?

**Comment by abhiandthetruth** [comment]
yup everything else is on point

**Comment by abhishekmsingh** [comment]
One more thing the script in the book.html should be in the file scripts/book.js . You should always perform this separation whenever necessary

**Comment by untrulynoxiusmj** [comment]
Ok sir

**Comment by untrulynoxiusmj** [comment]
live link :

https://untrulynoxiusmj.github.io/libook/pages/

**Pull request merged**
