### PR TITLE
updated index.html and index.js

### LINKED ISSUE #3: Make the search bar filter the titles
When searched with a query, only those titles should be visible which partially or completely matches the query ignoring the case. Do not redirect or load another page make the changes on the current page only. Please read how the data is getting stored in the local storage in the Readme.

### PR DESCRIPTION
**Pull request by griffy06**
__3__ 

Fixes #3

#### Short description of what this resolves:
Adds functionality to the search bar

#### Changes proposed in this pull request and/or Screenshots of changes:
event listener added to the search button
-
-
-

### CODE REVIEW

**Comment by abhishekmsingh** [comment]
Live link please

**Comment by abhishekmsingh** [comment]
@griffy06 For generating live link,
go to your repository settings, scroll down to github pages section and select master branch in the sources. The url you get just give me that.

**Comment by griffy06** [comment]
https://griffy06.github.io/libook/

**Comment by abhishekmsingh** [comment]
Nice work

**Pull request merged**
