### PR TITLE
Pdf Upload facility

### PR DESCRIPTION
**Pull request by pradhuman1**
__72__ 

#72

#### Short description of what this resolves:

Drag and Drop for pdf upload facility has been added 

#### Changes proposed in this pull request and/or Screenshots of changes:

-https://pradhuman1.github.io/libook/pages/
-
-

### CODE REVIEW

**Comment by abhishekmsingh** [comment]
Make the drag and drop ui better. Like it should change state when a file is hovered over it. Else everything looks fine.

**Comment by abhishekmsingh** [comment]
The hover effect  should be enabled only when a file is dragged on it.

**Comment by pradhuman1** [comment]
review now

**Comment by pradhuman1** [comment]
> review now

@abhiandthetruth

**Pull request merged**
