### PR TITLE
Prevent blank titles

### LINKED ISSUE #8: Prevent blank titles
Currently the title can be blank and still get added in the list. Prevent this action, and notify the user that title is empty by making the border of the text box momentarily red. You may add some text also to indicate it.

### PR DESCRIPTION
**Pull request by pradhuman1**
__8__ 

Fixes #8

#### Short description of what this resolves:

Blank Titles prevented along with a message

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Comment by pradhuman1** [comment]
https://pradhuman1.github.io/libook/pages/

**Comment by abhishekmsingh** [comment]
Why did you changed the class of text field from form-control to form-control-title? It lost its bootstrap 4 styling. It looks odd. Please give the reason to do so @pradhuman1.

**Comment by pradhuman1** [comment]
Sorry sir i have done it mistakenly,i will change it

**Comment by abhishekmsingh** [comment]
Also the border width is too big try reducing it and instead of
printing 'Blank!!' outside the text box you can make the text inside the
text box something like 'The title cannot be blank' in red maybe
momentarily. I think this will be a better option. What do you think?

**Comment by pradhuman1** [comment]
https://pradhuman1.github.io/libook/pages/

**Pull request merged**
